# Generated by Django 5.2.4 on 2026-06-23 10:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('passenger_adults', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('passenger_children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('passenger_infants', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('is_unaccompanied_minor', models.BooleanField(default=False, help_text='Booking includes unaccompanied minors')),
                ('is_group_booking', models.BooleanField(default=False, help_text='Booking is for a group')),
                ('is_emergency', models.BooleanField(default=False, help_text='Booking is for emergency travel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Required for infants', null=True)),
                ('passenger_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], max_length=20)),
                ('document', models.FileField(blank=True, help_text='Required for adults and children; not applicable for infants.', null=True, upload_to='passenger_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Status of document verification', max_length=20)),
                ('is_group_leader', models.BooleanField(default=False, help_text='Is this passenger the group leader?')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking')),
                ('linked_adult', models.ForeignKey(blank=True, help_text='Adult responsible for child/infant, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='bookings.passenger')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='group_leader',
            field=models.ForeignKey(blank=True, help_text='Designated group leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_bookings', to='bookings.passenger'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('local', 'Local')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=100, null=True, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField(help_text='Latitude of port (Fiji: -21 to -16)', validators=[django.core.validators.MinValueValidator(-21.0), django.core.validators.MaxValueValidator(-16.0)])),
                ('lng', models.FloatField(help_text='Longitude of port (Fiji: 176 to 181)', validators=[django.core.validators.MinValueValidator(176.0), django.core.validators.MaxValueValidator(181.0)])),
                ('operating_hours_start', models.TimeField(default=datetime.time(6, 0), help_text='Port opening time')),
                ('operating_hours_end', models.TimeField(default=datetime.time(20, 0), help_text='Port closing time')),
                ('berths', models.PositiveIntegerField(default=2, help_text='Number of simultaneous berths')),
                ('tide_sensitive', models.BooleanField(default=False, help_text='Port has reef/tide constraints')),
                ('night_ops_allowed', models.BooleanField(default=False, help_text='Allows night operations')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='bookings_po_name_ef7b2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cruise_speed_knots', models.FloatField(default=25.0, help_text='Cruising speed in knots', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('turnaround_minutes', models.PositiveIntegerField(default=480, help_text='Turnaround time in minutes')),
                ('max_daily_hours', models.FloatField(default=12.0, help_text='Max operating hours per day', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('overnight_allowed', models.BooleanField(default=False, help_text='Allows overnight trips')),
                ('home_port', models.ForeignKey(blank=True, help_text="Ferry's home port", null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.port')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_duration', models.DurationField(default='00:00:00')),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_tier', models.CharField(choices=[('major', 'Major'), ('regional', 'Regional'), ('remote', 'Remote')], default='regional', help_text='Route service tier for scheduling frequency', max_length=20)),
                ('min_weekly_services', models.PositiveIntegerField(default=7, help_text='Minimum weekly services')),
                ('preferred_departure_windows', models.JSONField(default=list, help_text="Preferred departure time windows (e.g., ['06:00-08:00', '12:00-14:00'])")),
                ('safety_buffer_minutes', models.PositiveIntegerField(default=15, help_text='Safety buffer in minutes for ETA')),
                ('waypoints', models.JSONField(default=list, help_text='Optional water waypoints for maritime route')),
                ('departure_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='bookings.port')),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='bookings.port')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('estimated_duration', models.CharField(blank=True, help_text="Estimated travel duration (e.g., '12 hours')", max_length=50)),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('operational_day', models.DateField(db_index=True, help_text='Date of operation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_by_auto', models.BooleanField(default=False, help_text='Created by auto-scheduler')),
                ('ferry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ferry')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.route')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.schedule'),
        ),
        migrations.CreateModel(
            name='ServicePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], help_text='Day of the week (aligned with ExtractWeekDay)')),
                ('window', models.CharField(help_text="Time window (e.g., '06:00-08:00')", max_length=20)),
                ('target_departures', models.PositiveIntegerField(default=1, help_text='Target number of departures')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('ticket_status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('qr_token', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle')], max_length=20)),
                ('dimensions', models.CharField(help_text='Vehicle dimensions in cm (e.g., 480x180x150)', max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wave_height', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('precipitation_probability', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_conditions', to='bookings.port')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_conditions', to='bookings.route')),
            ],
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_type', models.CharField(choices=[('premium_seating', 'Premium Seating'), ('priority_boarding', 'Priority Boarding'), ('cabin', 'Cabin'), ('meal_breakfast', 'Meal - Breakfast'), ('meal_lunch', 'Meal - Lunch'), ('meal_dinner', 'Meal - Dinner'), ('meal_snack', 'Meal - Snack')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the add-on')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this add-on currently available?')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='bookings.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['booking', 'add_on_type'], name='bookings_ad_booking_2aa859_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('general', 'General'), ('hazardous', 'Hazardous'), ('perishable', 'Perishable'), ('vehicle', 'Vehicle')], help_text='Type of cargo', max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('dimensions_cm', models.CharField(blank=True, help_text='e.g., 400x180x150', max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, help_text='Optional license plate for vehicles', max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='bookings.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['booking'], name='bookings_ca_booking_3deca8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when maintenance is completed', null=True)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=14, help_text='Custom maintenance interval in days')),
                ('ferry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='bookings.ferry')),
            ],
            options={
                'indexes': [models.Index(fields=['ferry', 'maintenance_date'], name='bookings_ma_ferry_i_055408_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['booking', 'passenger_type'], name='bookings_pa_booking_16bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'payment_status'], name='bookings_pa_booking_248c01_idx'),
        ),
        migrations.AddIndex(
            model_name='ferry',
            index=models.Index(fields=['name', 'is_active'], name='bookings_fe_name_960dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['departure_port', 'destination_port'], name='bookings_ro_departu_daf138_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('departure_port', 'destination_port')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['departure_time', 'status'], name='bookings_sc_departu_defa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['operational_day'], name='bookings_sc_operati_819a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booking_date'], name='bookings_bo_user_id_2f3cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_email', 'booking_date'], name='bookings_bo_guest_e_128a78_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepattern',
            index=models.Index(fields=['route', 'weekday'], name='bookings_se_route_i_f2c98e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking', 'qr_token'], name='bookings_ti_booking_40a5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['booking'], name='bookings_ve_booking_10a743_idx'),
        ),
        migrations.AddIndex(
            model_name='weathercondition',
            index=models.Index(fields=['route', 'port', 'expires_at'], name='bookings_we_route_i_f36967_idx'),
        ),
    ]
