# Generated by Django 5.2.4 on 2026-06-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__gte', 0)), name='schedule_available_seats_non_negative'),
        ),
    ]
