# Generated by Django 5.2.4 on 2026-06-23 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_schedule_schedule_available_seats_non_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
