# Generated by Django 5.2.4 on 2026-06-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('departed', 'Departed'), ('weather_hold', 'Weather Hold (needs review)')], default='scheduled', max_length=20),
        ),
    ]
