# Generated by Django 5.2.4 on 2026-06-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='dimensions_cm',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='dimensions',
        ),
    ]
