# Generated by Django 5.2.4 on 2026-06-28 00:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_cargo_dimensions_cm_remove_vehicle_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferry',
            name='max_cargo_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum cargo weight the vessel can carry (kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ferry',
            name='vehicle_capacity',
            field=models.PositiveIntegerField(default=20, help_text='Number of vehicle slots on the car deck'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='available_cargo_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Remaining cargo weight capacity in kg (seeded from the ferry's max_cargo_kg)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='available_vehicle_slots',
            field=models.PositiveIntegerField(default=0, help_text="Remaining vehicle slots (seeded from the ferry's vehicle_capacity)"),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('available_vehicle_slots__gte', 0)), name='schedule_available_vehicle_slots_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('available_cargo_kg__gte', 0)), name='schedule_available_cargo_kg_non_negative'),
        ),
    ]
