# Generated by Django 5.2.4 on 2026-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=30),
        ),
    ]
